printWidth: 100
trailingComma: 'es5'
tabWidth: 2
semi: true
singleQuote: true
quoteProps: 'as-needed'
jsxSingleQuote: true
bracketSpacing: true
arrowParens: 'always'
endOfLine: 'lf'
embeddedLanguageFormatting: auto
